<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MySqlConnector" Version="2.4.0" />
    <PackageReference Include="Confluent.Kafka" Version="2.15.1" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Data/schema.sql" CopyToOutputDirectory="PreserveNewest" />
    <EmbeddedResource Include="Development/*.html;Development/*.css;Development/*.js" />
  </ItemGroup>
</Project>
